# Render Blueprint: r:home EOD Web Dashboard
services:
  - type: web
    name: rhome-eod-dashboard
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: bash -lc 'ln -sf /data/eod.db ./eod.db; uvicorn app.main:app --host 0.0.0.0 --port $PORT'
    autoDeploy: true
    healthCheckPath: /health
    disk:
      name: eod-snapshots
      mountPath: /data
      sizeGB: 1
    envVars:
      - key: SIMPRO_BASE_URL
        value: https://rhome.simprosuite.com
      - key: SIMPRO_CLIENT_ID
        sync: false   # fill in on Render
      - key: SIMPRO_CLIENT_SECRET
        sync: false   # fill in on Render
      - key: SIMPRO_COMPANY_ID
        sync: false   # optional
      - key: SLACK_WEBHOOK_URL
        sync: false   # optional
      - key: TZ
        value: America/Chicago
cronJobs:
  - name: eod-live-ingest
    env: python
    plan: free
    buildCommand: echo "no build needed"
    # Call the web app's endpoint so the DB updates on the web service's disk
    startCommand: bash -lc 'curl -fsS -X POST "$DASHBOARD_URL/ingest/live" || exit 1'
    schedule: "0 22 * * *"   # 5:00 pm Chicago during Daylight Time (CDT)
    envVars:
      - key: DASHBOARD_URL
        fromService:
          name: rhome-eod-dashboard
          type: web
          property: url
