services:
  - type: web
    name: rhome-eod-dashboard
    env: python
    plan: starter
    buildCommand: pip install -r requirements.txt
    startCommand: bash -lc 'ln -sf /data/eod.db ./eod.db; uvicorn app.main:app --host 0.0.0.0 --port $PORT'
    healthCheckPath: /health
    disk:
      name: eod-snapshots
      mountPath: /data
      sizeGB: 1
    envVars:
      - key: SIMPRO_BASE_URL
        value: https://rhome.simprosuite.com
      - key: SIMPRO_CLIENT_ID
        sync: false
      - key: SIMPRO_CLIENT_SECRET
        sync: false
      - key: SIMPRO_COMPANY_ID
        sync: false
      - key: SLACK_WEBHOOK_URL
        sync: false
      - key: TZ
        value: America/Chicago

  - type: cron
    name: eod-live-ingest
    env: python
    plan: starter
    schedule: "0 22 * * *"  # ~5:00pm Chicago during daylight time
    buildCommand: "true"
    startCommand: bash -lc 'curl -fsS -X POST "http://$DASHBOARD_HOSTPORT/ingest/live" || exit 1'
    envVars:
      - key: DASHBOARD_HOSTPORT
        fromService:
          name: rhome-eod-dashboard
          type: web
          property: hostport
